---
extends: default

rules:
  line-length:
    max: 160
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: enable
