---
galaxy_info:
  author: richmuscle
  role_name: backup
  namespace: ferro43
  description: "Backup and recovery tooling"
  license: MIT
  min_ansible_version: "2.17"
  platforms:
    - name: Fedora
      versions:
        - all
dependencies: []
